<?php
/**
 * DefaultApi
 * PHP version 5
 *
 * @category Class
 * @package  PflegeDe\Partner
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * pflege.de partner API
 *
 * The Partner-API of pflege.de to create Affiliate-Leads programmatically
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PflegeDe\Partner\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use PflegeDe\Partner\ApiException;
use PflegeDe\Partner\Configuration;
use PflegeDe\Partner\HeaderSelector;
use PflegeDe\Partner\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  PflegeDe\Partner
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation helloWorldGet
     *
     *
     * @throws \PflegeDe\Partner\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function helloWorldGet()
    {
        $this->helloWorldGetWithHttpInfo();
    }

    /**
     * Operation helloWorldGetWithHttpInfo
     *
     *
     * @throws \PflegeDe\Partner\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function helloWorldGetWithHttpInfo()
    {
        $returnType = '';
        $request = $this->helloWorldGetRequest();

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation helloWorldGetAsync
     *
     * 
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function helloWorldGetAsync()
    {
        return $this->helloWorldGetAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation helloWorldGetAsyncWithHttpInfo
     *
     * 
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function helloWorldGetAsyncWithHttpInfo()
    {
        $returnType = '';
        $request = $this->helloWorldGetRequest();

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'helloWorldGet'
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function helloWorldGetRequest()
    {

        $resourcePath = '/hello-world';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation leadHausnotrufPost
     *
     * @param  string $partnerId partnerId (required)
     * @param  \PflegeDe\Partner\Model\Hausnotruf $body body (required)
     * @param  bool $debug Der Lead wird zwar gespeichert, intern aber nicht weiterverteilt und auch keine Affiliate-Transaktion angelegt (optional)
     *
     * @throws \PflegeDe\Partner\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function leadHausnotrufPost($partnerId, $body, $debug = null)
    {
        $this->leadHausnotrufPostWithHttpInfo($partnerId, $body, $debug);
    }

    /**
     * Operation leadHausnotrufPostWithHttpInfo
     *
     * @param  string $partnerId (required)
     * @param  \PflegeDe\Partner\Model\Hausnotruf $body (required)
     * @param  bool $debug Der Lead wird zwar gespeichert, intern aber nicht weiterverteilt und auch keine Affiliate-Transaktion angelegt (optional)
     *
     * @throws \PflegeDe\Partner\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function leadHausnotrufPostWithHttpInfo($partnerId, $body, $debug = null)
    {
        $returnType = '';
        $request = $this->leadHausnotrufPostRequest($partnerId, $body, $debug);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation leadHausnotrufPostAsync
     *
     * 
     *
     * @param  string $partnerId (required)
     * @param  \PflegeDe\Partner\Model\Hausnotruf $body (required)
     * @param  bool $debug Der Lead wird zwar gespeichert, intern aber nicht weiterverteilt und auch keine Affiliate-Transaktion angelegt (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function leadHausnotrufPostAsync($partnerId, $body, $debug = null)
    {
        return $this->leadHausnotrufPostAsyncWithHttpInfo($partnerId, $body, $debug)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation leadHausnotrufPostAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $partnerId (required)
     * @param  \PflegeDe\Partner\Model\Hausnotruf $body (required)
     * @param  bool $debug Der Lead wird zwar gespeichert, intern aber nicht weiterverteilt und auch keine Affiliate-Transaktion angelegt (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function leadHausnotrufPostAsyncWithHttpInfo($partnerId, $body, $debug = null)
    {
        $returnType = '';
        $request = $this->leadHausnotrufPostRequest($partnerId, $body, $debug);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'leadHausnotrufPost'
     *
     * @param  string $partnerId (required)
     * @param  \PflegeDe\Partner\Model\Hausnotruf $body (required)
     * @param  bool $debug Der Lead wird zwar gespeichert, intern aber nicht weiterverteilt und auch keine Affiliate-Transaktion angelegt (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function leadHausnotrufPostRequest($partnerId, $body, $debug = null)
    {
        // verify the required parameter 'partnerId' is set
        if ($partnerId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $partnerId when calling leadHausnotrufPost'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling leadHausnotrufPost'
            );
        }

        $resourcePath = '/lead/hausnotruf';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($partnerId !== null) {
            $queryParams['partner_id'] = ObjectSerializer::toQueryValue($partnerId);
        }
        // query params
        if ($debug !== null) {
            $queryParams['debug'] = ObjectSerializer::toQueryValue($debug);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation leadTreppenliftPost
     *
     * @param  string $partnerId partnerId (required)
     * @param  \PflegeDe\Partner\Model\Treppenlift $body body (required)
     * @param  bool $debug Der Lead wird zwar gespeichert, intern aber nicht weiterverteilt und auch keine Affiliate-Transaktion angelegt (optional)
     *
     * @throws \PflegeDe\Partner\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function leadTreppenliftPost($partnerId, $body, $debug = null)
    {
        $this->leadTreppenliftPostWithHttpInfo($partnerId, $body, $debug);
    }

    /**
     * Operation leadTreppenliftPostWithHttpInfo
     *
     * @param  string $partnerId (required)
     * @param  \PflegeDe\Partner\Model\Treppenlift $body (required)
     * @param  bool $debug Der Lead wird zwar gespeichert, intern aber nicht weiterverteilt und auch keine Affiliate-Transaktion angelegt (optional)
     *
     * @throws \PflegeDe\Partner\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function leadTreppenliftPostWithHttpInfo($partnerId, $body, $debug = null)
    {
        $returnType = '';
        $request = $this->leadTreppenliftPostRequest($partnerId, $body, $debug);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation leadTreppenliftPostAsync
     *
     * 
     *
     * @param  string $partnerId (required)
     * @param  \PflegeDe\Partner\Model\Treppenlift $body (required)
     * @param  bool $debug Der Lead wird zwar gespeichert, intern aber nicht weiterverteilt und auch keine Affiliate-Transaktion angelegt (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function leadTreppenliftPostAsync($partnerId, $body, $debug = null)
    {
        return $this->leadTreppenliftPostAsyncWithHttpInfo($partnerId, $body, $debug)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation leadTreppenliftPostAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $partnerId (required)
     * @param  \PflegeDe\Partner\Model\Treppenlift $body (required)
     * @param  bool $debug Der Lead wird zwar gespeichert, intern aber nicht weiterverteilt und auch keine Affiliate-Transaktion angelegt (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function leadTreppenliftPostAsyncWithHttpInfo($partnerId, $body, $debug = null)
    {
        $returnType = '';
        $request = $this->leadTreppenliftPostRequest($partnerId, $body, $debug);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'leadTreppenliftPost'
     *
     * @param  string $partnerId (required)
     * @param  \PflegeDe\Partner\Model\Treppenlift $body (required)
     * @param  bool $debug Der Lead wird zwar gespeichert, intern aber nicht weiterverteilt und auch keine Affiliate-Transaktion angelegt (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function leadTreppenliftPostRequest($partnerId, $body, $debug = null)
    {
        // verify the required parameter 'partnerId' is set
        if ($partnerId === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $partnerId when calling leadTreppenliftPost'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling leadTreppenliftPost'
            );
        }

        $resourcePath = '/lead/treppenlift';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($partnerId !== null) {
            $queryParams['partner_id'] = ObjectSerializer::toQueryValue($partnerId);
        }
        // query params
        if ($debug !== null) {
            $queryParams['debug'] = ObjectSerializer::toQueryValue($debug);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
